/// EnemiesArenaAddEnemy(number, x, y, object, health, phase)
EnemiesArenaAddEnemy(0, x, y, objEnemyEggpawn, 0, 0)
EnemiesArenaAddEnemy(1, x + 500, y, objEnemyEggpawn, 0, 0)
EnemiesArenaAddEnemy(2, x + 128, y, objEnemyEggpawn, 0, 0)
EnemiesArenaAddEnemy(3, x + 300, y, objEnemyHeavy, 3, 0)
EnemiesArenaAddEnemy(4, x + 400, y + 60, objEnemySpinner, 0, 0)

EnemiesArenaAddEnemy(5, x + 128, y, objEnemyHeavy, 3, 1)
EnemiesArenaAddEnemy(6, x + 48, y, objEnemyHeavy, 3, 1)
EnemiesArenaAddEnemy(7, x + 50, y, objEnemyEggpawn, 0, 1)
EnemiesArenaAddEnemy(8, x + 78, y, objEnemyEggpawn, 0, 1)
